### ISSUE TITLE
stpyfits uses private classes + methods fits.hdu.image._ImageBaseHDU._summary and fails

### ISSUE THREAD

**Issue by olebole** [spacetelescope/stsci.tools#47]
I am just trying to create a Debian package from stsci.tools (to use with pyraf), and found that `lib/stsci/tools/stpyfits.py ` accesses methods that are for astropy internal use only. Namely `astropy.io.fits.hdu.image._ImageBaseHDU`, and its method `_summary()`. The latter fails with newer astropy versions (tested with 2.0.2), since it introduced an additional member in the middle, which makes the overwriting fail:

```
    def _summary(self):
        summ = super(_ConstantValueImageBaseHDU, self)._summary()
        return (summ[0], summ[1].replace('ConstantValue', '')) + summ[2:]
```

```
ERROR: Test the info convience function in both the fits and stpyfits
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/stsci.tools-3.4.11/.pybuild/pythonX.Y_2.7/build/stsci/tools/tests/testStpyfits.py", line 31, in testInfoConvienceFunction
    stpyfits.info(self.data('o4sp040b0_raw.fits'), output=False),
  File "/build/stsci.tools-3.4.11/.pybuild/pythonX.Y_2.7/build/stsci/tools/stpyfits.py", line 55, in wrapped_with_stpyfits
    retval = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/astropy/io/fits/convenience.py", line 704, in info
    ret = f.info(output=output)
  File "/usr/lib/python2.7/dist-packages/astropy/io/fits/hdu/hdulist.py", line 953, in info
    summary = hdu._summary()
  File "/build/stsci.tools-3.4.11/.pybuild/pythonX.Y_2.7/build/stsci/tools/stpyfits.py", line 288, in _summary
    return (summ[0], summ[1].replace('ConstantValue', '')) + summ[2:]
AttributeError: 'int' object has no attribute 'replace'
```

After fixing this, many of the tests fail since they do not take into account the additional tuple member.

**Comment by pllim** [comment]
xref astropy/astropy#6124
