### ISSUE TITLE
Tests with nose-1.3.7 fail

### ISSUE THREAD

**Issue by olebole** [spacetelescope/stsci.tools#49]
When using nose-1.3.7, I get the following test failures (not sure whether they may be a bug of nose, however):

```
ERROR: Purpose:
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test() takes at least 1 argument (0 given)

======================================================================
ERROR: Build and run the suite through the testrunner. Verbosity level
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: testall() takes at least 1 argument (0 given)

======================================================================
ERROR: stsci.tools.testutil.testlog
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: testlog() takes at least 1 argument (0 given)
```

**Comment by pllim** [comment]
Fixed by #61 . The test suite no longer depends on `nose`.
